const express = require('express');
const mongoose = require('mongoose');
const cors = require('cors');
const dotenv = require('dotenv');
const path = require('path');
dotenv.config();
const app = express();
app.use(express.json());
app.use(cors());
app.use('/uploads', express.static(path.join(__dirname, 'uploads')));
const mongoUri = process.env.MONGO_URI || 'mongodb://localhost:27017/linkedin_clone';
mongoose.connect(mongoUri, { useNewUrlParser: true, useUnifiedTopology: true }).then(()=>console.log('mongodb connected')).catch(err=>{console.error(err); process.exit(1);} );
app.use('/api/auth', require('./routes/auth'));
app.use('/api/posts', require('./routes/posts'));
app.use('/api/users', require('./routes/users'));
const PORT = process.env.PORT || 5000;
app.listen(PORT, ()=>console.log(`server ${PORT}`));
